#include "moca/core/latest_value.hpp"
#include "moca/capture/gstreamer_capture.hpp"
#include "moca/hand_tracking/association.hpp"
#include "moca/hand_tracking/wrist_hand_tracker.hpp"
#include "moca/tracking/identity_tracker.hpp"
#include <cassert>
#include <chrono>
int main(){moca::LatestValue<int> slot;assert(!slot.newer_than(0));slot.replace(1);slot.replace(2);auto latest=slot.newer_than(0);assert(latest&&latest->first==2&&latest->second==2);moca::IdentityTracker tracker;auto now=std::chrono::steady_clock::now();moca::Detection left{},right{};left.box={0,0,100,200};right.box={300,0,400,200};left.confidence=0.8F;left.keypoints[9]={0.4F,0.5F,0.9F};left.keypoints[7]={0.3F,0.5F,0.8F};auto first=tracker.update({right,left},now);assert(first[0].id==0&&first[1].id==1);moca::WristHandTracker hand_tracker;const moca::ImageView empty{{},0,0,0};const auto hands=hand_tracker.infer(empty,first);assert(hands.size()==1);assert(hands[0].id==1&&hands[0].person_id==1);assert(hands[0].center.x>0.4F);assert(hands[0].confidence>0.71F&&hands[0].confidence<0.73F);std::vector<moca::HandObservation> detected{{1000,0,{0.39F,0.5F,1.0F},{},1.0F},{1001,0,{0.41F,0.5F,1.0F},{},1.0F}};const auto associated=moca::associate_hands_to_wrists(std::move(detected),first);assert(associated.size()==1);assert(associated[0].id==1&&associated[0].person_id==1);const auto unidentified=moca::associate_hands_to_wrists({{1000,0,{0.9F,0.9F,1.0F},{},1.0F}},first);assert(unidentified.empty());tracker.update({},now+std::chrono::milliseconds(1100));assert(tracker.active_tracks()==0);
std::string error;moca::GStreamerCapture capture("videotestsrc num-buffers=1 ! videoconvert ! video/x-raw,format=RGB ! appsink name=sink");assert(capture.start(error));auto frame=capture.pull(std::chrono::seconds(2),error);assert(frame&&frame->width>0&&frame->height>0&&!frame->pixels.empty());capture.stop();}
